### ISSUE TITLE
step id can not end with "on"

### ISSUE THREAD

**Issue by theowenyoung** [actionsflow/actionsflow#14]
## Description

Step name can not end with "on", like "translation", it will parse it to `translatiundefined`

```yaml
on:
  workflow_dispatch:
jobs:
  translation:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Translate to ZH
        id: translation
        uses: fabasoad/translation-action@main
        with:
          source: test
      - name: Print translation result
         run: echo "${{ steps.translation.outputs.text }}"
```

`on` is a keyword of Actionsflow, it should check the regex rule.
