### ISSUE TITLE
Run act step in GitHub action gives an error

### ISSUE THREAD

**Issue by NotReallyEight** [actionsflow/actionsflow#33]
## Description

After running a GitHub action using the Instagram trigger, I've faced the following error in the `Run act` GitHub action step.

```powershell
[0-instagram-instagram.yml/Print 0] 🚀  Start image=actionsflow/act-environment:v1
[0-instagram-instagram.yml/Print 0]   🐳  docker pull image=actionsflow/act-environment:v1 platform= username= forcePull=false
[0-instagram-instagram.yml/Print 0]   🐳  docker create image=actionsflow/act-environment:v1 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[0-instagram-instagram.yml/Print 0]   🐳  docker run image=actionsflow/act-environment:v1 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[0-instagram-instagram.yml/Print 0]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
time="2022-02-14T20:31:59Z" level=fatal msg="yaml: unmarshal errors:\n  line 11: cannot unmarshal !!map into string"
```

### Steps to reproduce

Create a `instagram.yml` file with the following content:

```yml
on:
  instagram:
    access_token: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
    user_id: ${{ secrets.INSTAGRAM_USER_ID }}
    fetchAllResultsAtFirst: true
    maxCount: 1000

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          outputs: { { toJSON(on.instagram.outputs) } }
        run: echo $outputs
```

Make an Instagram post so that the triggered workflow gets ran.

See the action failing.

### Expected result

The GitHub action should not have any issues and should return what the action file says.

### Actual result

The GitHub action fails and exits with status code `1`.

**Comment by theowenyoung** [comment]
Maybe your prettier format the yaml code by mistakes, 

it should be `{{` , not `{ {`, or you can add `"` for the string to avoid prettier format.

```yaml
on:
  instagram:
    access_token: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
    user_id: ${{ secrets.INSTAGRAM_USER_ID }}
    fetchAllResultsAtFirst: true
    maxCount: 1000

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          outputs: "{{ toJSON(on.instagram.outputs) }}"
        run: echo $outputs
```
