### ISSUE TITLE
Multiple rss feeds as trigger returns error

### ISSUE THREAD

**Issue by MarcMogdanz** [actionsflow/actionsflow#4]
## Description

When I'm using three urls for my RSS trigger it works fine. When I add another one it will fail and throw an error `OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: argument list too long: unknown`. This also happens when I use multiple RSS triggers in different workflows as long as they have all together four urls.

This [commit](https://github.com/MarcMogdanz/actionsflow-workflows/commit/f58bd7f2712e5c3ba856184f323ac9ae12b29401) adds two urls so that the workflow has four urls together. This [workflow run](https://github.com/MarcMogdanz/actionsflow-workflows/runs/1202603806?check_suite_focus=true) was before the commit and everything was fine. This [workflow run](https://github.com/MarcMogdanz/actionsflow-workflows/runs/1202605540?check_suite_focus=true) was after the commit and throw the error.

### Steps to reproduce

1. Create a workflow with a RSS trigger with at least four urls
2. Trigger the workflow

### Expected result

All four urls should be crawled and the workflow should be executed.

### Actual result

The workflow throws an error and fails.

**Comment by theowenyoung** [comment]
It looks like an act run error, let me check where is wrong.

**Comment by theowenyoung** [comment]
Hey, @MarcMogdanz , it looks like the built workflow.yml (when the first time fetch multiple feeds) is too large for [act](https://github.com/nektos/act), you can change your `hn.yml` to this:

```yaml
on:
  rss:
    url:
      # HN posts with over 500 points
      - https://hnrss.org/newest?points=500
      # Show HN posts with over 100 points
      - https://hnrss.org/show?points=100
      #
      #
      #
      # Dev blog to an interesting upcoming german Minecraft server
      - https://blog.playlegend.net/rss
      # test
      - https://dev.to/feed/tag/javascript
    config:
      filterOutputs:
        title: 1
        link: 1
      format: |
        // extract hostname from full url
        item.hostname = new URL(item.link).hostname
        return item;
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      # Used for debugging
      - name: Print to console
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
          hostname: ${{ on.rss.outputs.hostname }}
        run: |
          echo title: $title
          echo link: $link
          echo hostname: $hostname
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RSS }}
        uses: Ilshidur/action-slack@2.1.0
        with:
          args: |
            *${{ on.rss.outputs.title }}* (`${{ on.rss.outputs.hostname }}`)
            ${{ on.rss.outputs.link }}
```

Use [`on.<trigger>.config.filterOutputs`](https://actionsflow.github.io/docs/workflow/#ontriggerconfigfilteroutputs) to reduce the built yml size.

Or, you can set [`skipFirst: true`](https://actionsflow.github.io/docs/workflow/#ontriggerconfigskipfirst) to avoid the first time large outputs.

I have already try this config, it works fine. I'll add a doc to note people to avoid big outputs.

> You may need to [reset the actionsflow cache](https://actionsflow.github.io/docs/reference/github-workflow/#actionsflow-reset-cacheyml) to rerun the first time feed fetching.
