### ISSUE TITLE
When using multi rss feed trigger, only the first rss feed triggers the action

### ISSUE THREAD

**Issue by ss-zheng** [actionsflow/actionsflow#49]
## Description

When using multi rss feed trigger, only the first rss feed triggers the action

### Steps to reproduce

```
on:
  rss:
    url:
      - https://www.apartmenttherapy.com/main.rss
      - https://stylebyemilyhenderson.com/feed
      - https://feeds.feedburner.com/younghouselove
      - https://cococozy.com/feed/
    config:
      limit: 30
      every: "*/5 * * * *" # every 5 mins
```
^ here is my rss.yml file

### Expected result
I expect this should trigger not just for the first rss feed, but also all the rss feed listed

### Actual result
Only the first url in the list triggers my action
